// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrknfweilbuwrhzzwnrr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlya25md2VpbGJ1d3Joenp3bnJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3MjkwODksImV4cCI6MjA4MzMwNTA4OX0.djk3RquoU5Bu-cTF6BTgu2RKYQ7vh-E5HgkLBuR9sNQ";

// Validação de chaves
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Chaves do Supabase não configuradas');
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  },
  db: {
    schema: "public",
  },
  global: {
    headers: {
      "X-Client-Info": "supabase-js-web",
    },
  },
});

// Monitorar eventos de autenticação
supabase.auth.onAuthStateChange((event, session) => {
  if (event === 'TOKEN_REFRESHED') {
    console.log('Token atualizado');
  } else if (event === 'SIGNED_OUT') {
    console.log('Usuário desconectado');
  } else if (event === 'SIGNED_IN') {
    console.log('Usuário autenticado');
  }
});

// Conexão estabelecida - sem health check
console.log("✅ Cliente Supabase inicializado");